// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ69KD70KeUgqeF4pe1OxYzEX5hmSb8xw',
    appId: '1:804156325159:web:250dd872b711b20240bd02',
    messagingSenderId: '804156325159',
    projectId: 'unikatko-1239b',
    authDomain: 'unikatko-1239b.firebaseapp.com',
    storageBucket: 'unikatko-1239b.appspot.com',
    measurementId: 'G-P7EX9MEGG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDupwx8QZ4npVLdKYqkJBm16yk8DufvqNs',
    appId: '1:804156325159:android:1723de5896a19a3740bd02',
    messagingSenderId: '804156325159',
    projectId: 'unikatko-1239b',
    storageBucket: 'unikatko-1239b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhz9FooyNpdEyTYVQh5UP5fdLnW46xbCI',
    appId: '1:804156325159:ios:aa0848360d52ed6c40bd02',
    messagingSenderId: '804156325159',
    projectId: 'unikatko-1239b',
    storageBucket: 'unikatko-1239b.appspot.com',
    iosClientId:
        '804156325159-6a2m9bt63kjoqhpo2ccrmm2ug4braofl.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhz9FooyNpdEyTYVQh5UP5fdLnW46xbCI',
    appId: '1:804156325159:ios:990474c4e0dd5ec440bd02',
    messagingSenderId: '804156325159',
    projectId: 'unikatko-1239b',
    storageBucket: 'unikatko-1239b.appspot.com',
    iosClientId:
        '804156325159-k1cnmtdo77ndgc7tttph2ljnqlbcl6s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
