name: app
description: Your app description
version: 1.0.5+6


environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.2
  webview_flutter: ^3.0.0
  http: ^0.13.4
  flutter_webview_plugin: ^0.4.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

